name: Main Documentation
run-name: Bulging documentation for new release

on:
  workflow_run:
    workflows: ["Release"]
    branches: [master]
    types:
      - completed

  # For debug reasons, will be deleted
  push:
    branches:
      - documentation-main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup packages
        run: npm ci
      - name: Lint
        run: npm run lint

      - name: Spatial Docs
        run: npm run docs:build

      - name: Install s3cmd
        run: |
          pip3 install s3cmd
      - name: s3 Upload documentation build
        run: >
          s3cmd
          --access_key ${{ secrets.AWS_ACCESS_KEY_ID }}
          --secret_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          --host ${{ secrets.AWS_ENDPOINT }}
          --host-bucket ${{ secrets.AWS_ENDPOINT }}
          --bucket-location ${{ secrets.AWS_REGION }}
          --signature-v2
          --delete-removed
          --no-mime-magic
          sync
          ./docs/
          s3://${{ secrets.AWS_S3_BUCKET_2 }}/spatial/
